name: Build Newifi-D2 Passwall2
on:
  workflow_dispatch
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 420
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Maximize build space
        uses: easimon/maximize-build-space@v11
        with:
          remove-dotnet: true
          remove-android: true
          remove-haskell: true

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk gettext git libncurses-dev libssl-dev python3 python3-pip unzip wget zlib1g-dev

      - name: Clone ImmortalWrt
        run: git clone --depth 1 --branch v24.10.6 https://github.com/immortalwrt/immortalwrt.git

      - name: Generate .config
        working-directory: immortalwrt
        run: echo "Q09ORklHX1RBUkdFVF9yYW1pcHM9eQpDT05GSUdfVEFSR0VUX3JhbGlwc19tdDc2MjE9eQpDT05GSUdfVEFSR0VUX3JhbGlwc19tdDc2MjFfREVWSUNFX2QtdGVhbV9uZXdpaGktZDI9eQpDT05GSUdfUEFDQ0FHRV9sdWNpPXkKQ09ORklHX0xVQ0lfT0FOR196aF9IYW5zPXkKQ09ORklHX1BBQ0tBR0VfbHVjaS1pMThuLWJhc2UtemgtY249eQpDT05GSUdfUEFDQ0FHRV9sdWNpLWFwcC1wYXNzd2FsbDI9eQpDT05GSUdfUEFDQ0FHRV9sdWNpLWkxOG4tcGFzc3dhbGwyLXpoLWNuPXkKQ09ORklHX1BBQ0tBR0VfbHVjaS1hcHAtcGFzc3dhbGwyX0lOQ0xVRGVfWHJheT15CkNPTkZJR19DQ0FDSEU9eQo=" | base64 -d > .config

      - name: Add passwall feeds
        working-directory: immortalwrt
        run: |
          ./scripts/feeds add -f passwall2 https://github.com/xiaorouji/openwrt-passwall2.git^main
          ./scripts/feeds add -f passwall_pkgs https://github.com/xiaorouji/openwrt-passwall-packages.git^0eed799ea1ff165ab8df899e08038c3879f6ce95
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Defconfig
        working-directory: immortalwrt
        run: make defconfig

      - name: Download
        working-directory: immortalwrt
        run: make download -j$(nproc)

      - name: Compile
        working-directory: immortalwrt
        run: make -j$(nproc) || make -j1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Newifi3-ImmortalWrt-Passwall2
          retention-days: 7
          path: immortalwrt/bin/targets/ramips/mt7621/*.bin
